# Generated by Django 5.1.7 on 2025-05-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_coursesubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
